/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import model.Address;
import model.Doctor;
import model.Driver;
import model.Insurance;
import model.Patient;
import model.Person;
import model.VehicleRegistration;

/**
 *
 * @author advai
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
     Patient patient;
     Person person;
     Driver driver;
     VehicleRegistration vehicleregistration;
     Address address;
     Doctor doctor;
     Insurance insurance;
     
     
    public MainJFrame() {
        initComponents();
        patient =new Patient();
        person =new Person();
        driver =new Driver();
        vehicleregistration = new VehicleRegistration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        PersonalDetails = new javax.swing.JButton();
        Ambulancedriverdetails = new javax.swing.JButton();
        AmbulanceVehicle = new javax.swing.JButton();
        Add_Doc_Insu = new javax.swing.JButton();
        Viewreport = new javax.swing.JButton();
        PatientDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        PersonalDetails.setBackground(new java.awt.Color(204, 204, 204));
        PersonalDetails.setText("Person");
        PersonalDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalDetailsActionPerformed(evt);
            }
        });

        Ambulancedriverdetails.setBackground(new java.awt.Color(204, 204, 204));
        Ambulancedriverdetails.setText("Driver");
        Ambulancedriverdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulancedriverdetailsActionPerformed(evt);
            }
        });

        AmbulanceVehicle.setBackground(new java.awt.Color(204, 204, 204));
        AmbulanceVehicle.setText("VehicleRegistration");
        AmbulanceVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmbulanceVehicleActionPerformed(evt);
            }
        });

        Add_Doc_Insu.setBackground(new java.awt.Color(204, 204, 204));
        Add_Doc_Insu.setText("OtherInformation");
        Add_Doc_Insu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_Doc_InsuActionPerformed(evt);
            }
        });

        Viewreport.setBackground(new java.awt.Color(204, 204, 204));
        Viewreport.setText("PatientReport");
        Viewreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewreportActionPerformed(evt);
            }
        });

        PatientDetails.setBackground(new java.awt.Color(204, 204, 204));
        PatientDetails.setText("Patient");
        PatientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Add_Doc_Insu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AmbulanceVehicle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PatientDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PersonalDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ambulancedriverdetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Viewreport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(PatientDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonalDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ambulancedriverdetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AmbulanceVehicle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Add_Doc_Insu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(Viewreport)
                .addGap(63, 63, 63))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(2000, 2500));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PatientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientDetailsActionPerformed
        // TODO add your handling code here:
        
        PatientPanel patientpanel = new PatientPanel(patient);
        jSplitPane1.setRightComponent(patientpanel);
    }//GEN-LAST:event_PatientDetailsActionPerformed

    private void PersonalDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalDetailsActionPerformed
        // TODO add your handling code here:
        
        PersonalPanel personalpanel =new PersonalPanel(person);
        jSplitPane1.setRightComponent(personalpanel);
        
    }//GEN-LAST:event_PersonalDetailsActionPerformed

    private void ViewreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewreportActionPerformed
        // TODO add your handling code here:
        //ViewReport viewreport =new ViewReport(patient,person);
        ViewTryReport viewtryreport = new ViewTryReport(patient,person,driver,vehicleregistration,address,doctor,insurance);
        jSplitPane1.setRightComponent(viewtryreport);
        
    }//GEN-LAST:event_ViewreportActionPerformed

    private void AmbulancedriverdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulancedriverdetailsActionPerformed
        // TODO add your handling code here:
        DriverPanel driverpanel =new DriverPanel(driver);
        jSplitPane1.setRightComponent(driverpanel);
    }//GEN-LAST:event_AmbulancedriverdetailsActionPerformed

    private void AmbulanceVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmbulanceVehicleActionPerformed
        // TODO add your handling code here:
        
        VehicleregPanel vehicleregpanel = new VehicleregPanel(vehicleregistration);
        jSplitPane1.setRightComponent(vehicleregpanel);
    }//GEN-LAST:event_AmbulanceVehicleActionPerformed

    private void Add_Doc_InsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_Doc_InsuActionPerformed
        // TODO add your handling code here:
        
        OtherInformationPanel otherinformationpanel = new OtherInformationPanel(address,doctor,insurance);
        jSplitPane1.setRightComponent(otherinformationpanel);
    }//GEN-LAST:event_Add_Doc_InsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_Doc_Insu;
    private javax.swing.JButton AmbulanceVehicle;
    private javax.swing.JButton Ambulancedriverdetails;
    private javax.swing.JButton PatientDetails;
    private javax.swing.JButton PersonalDetails;
    private javax.swing.JButton Viewreport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
