/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.Address;
import model.Doctor;
import model.Insurance;

/**
 *
 * @author advai
 */
public class OtherInformationPanel extends javax.swing.JPanel {

    /**
     * Creates new form OtherInformationPanel
     */
    
    Address address;
    Doctor doctor;
    Insurance insurance;
    public OtherInformationPanel(Address address,Doctor doctor,Insurance insurance) {
        initComponents();
        this.address = address;
        this.doctor = doctor;
        this.insurance = insurance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        Address2 = new javax.swing.JLabel();
        Doornum2 = new javax.swing.JLabel();
        Streetname2 = new javax.swing.JLabel();
        Areaname2 = new javax.swing.JLabel();
        Cityname2 = new javax.swing.JLabel();
        State2 = new javax.swing.JLabel();
        Country2 = new javax.swing.JLabel();
        Zipcode2 = new javax.swing.JLabel();
        Doornumd1 = new javax.swing.JTextField();
        Streetnamed1 = new javax.swing.JTextField();
        Areanamed1 = new javax.swing.JTextField();
        Citynamed1 = new javax.swing.JTextField();
        Statenamed1 = new javax.swing.JTextField();
        countryd1 = new javax.swing.JTextField();
        Zipcoded1 = new javax.swing.JTextField();
        DocInfo2 = new javax.swing.JLabel();
        DocID2 = new javax.swing.JLabel();
        Dfn2 = new javax.swing.JLabel();
        Dln2 = new javax.swing.JLabel();
        Hospitalname2 = new javax.swing.JLabel();
        Departmentname2 = new javax.swing.JLabel();
        DoctormailID2 = new javax.swing.JLabel();
        Doctorphonenum2 = new javax.swing.JLabel();
        Doc1Dd1 = new javax.swing.JTextField();
        Dfnd1 = new javax.swing.JTextField();
        Dlnd1 = new javax.swing.JTextField();
        Hospitalnamed1 = new javax.swing.JTextField();
        Departmentnamed1 = new javax.swing.JTextField();
        DoctormailIDd1 = new javax.swing.JTextField();
        Doctorphonenumd1 = new javax.swing.JTextField();
        Insurancedetails2 = new javax.swing.JLabel();
        CorporateID2 = new javax.swing.JLabel();
        AddressID2 = new javax.swing.JLabel();
        PremiumID2 = new javax.swing.JLabel();
        DeductableID2 = new javax.swing.JLabel();
        TaxBenefitsID2 = new javax.swing.JLabel();
        SAVE2 = new javax.swing.JButton();
        COIDd1 = new javax.swing.JTextField();
        AddIDd1 = new javax.swing.JTextField();
        PreIDd1 = new javax.swing.JTextField();
        DedIdd1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Taxbend1 = new javax.swing.JTextArea();

        Address2.setText("Address");

        Doornum2.setText("DoorNum:");

        Streetname2.setText("StreetName:");

        Areaname2.setText("AreaName:");

        Cityname2.setText("CityName:");

        State2.setText("State:");

        Country2.setText("Country:");

        Zipcode2.setText("Zipcode:");

        DocInfo2.setText("Doctorinformation");

        DocID2.setText("DoctorID:");

        Dfn2.setText("FirstName:");

        Dln2.setText("LastName:");

        Hospitalname2.setText("HospitalName:");

        Departmentname2.setText("DepartmentName:");

        DoctormailID2.setText("DoctormailID:");

        Doctorphonenum2.setText("Doctorphonenum:");

        Insurancedetails2.setText("Insurancedetails");

        CorporateID2.setText("CorporateID:");

        AddressID2.setText("Address:");

        PremiumID2.setText("Premium:");

        DeductableID2.setText("Deductable:");

        TaxBenefitsID2.setText("TaxBenefits:");

        SAVE2.setText("SAVE");

        Taxbend1.setColumns(20);
        Taxbend1.setRows(5);
        jScrollPane3.setViewportView(Taxbend1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SAVE2)
                .addGap(201, 201, 201))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(Address2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressID2)
                                            .addComponent(PremiumID2)
                                            .addComponent(DeductableID2)
                                            .addComponent(TaxBenefitsID2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DedIdd1)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(PreIDd1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(AddIDd1))
                                                .addGap(1, 1, 1))
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CorporateID2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(COIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(Insurancedetails2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(DocInfo2)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Zipcode2)
                                    .addComponent(Country2)
                                    .addComponent(State2)
                                    .addComponent(Cityname2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Citynamed1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(Statenamed1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(countryd1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Zipcoded1, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Areaname2)
                                .addGap(104, 104, 104)
                                .addComponent(Areanamed1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Doornum2)
                            .addComponent(Streetname2))
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Streetnamed1)
                            .addComponent(Doornumd1))))
                .addGap(101, 101, 101))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Dfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Departmentnamed1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Doc1Dd1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DoctormailIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Hospitalnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dfnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dlnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Doctorphonenumd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Doctorphonenum2)
                            .addComponent(DoctormailID2)
                            .addComponent(Departmentname2)
                            .addComponent(Hospitalname2)
                            .addComponent(Dln2)
                            .addComponent(DocID2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Address2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Doornum2)
                            .addComponent(Doornumd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Streetname2)
                        .addGap(6, 6, 6))
                    .addComponent(Streetnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Areaname2)
                    .addComponent(Areanamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cityname2)
                    .addComponent(Citynamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State2)
                    .addComponent(Statenamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Country2)
                    .addComponent(countryd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Zipcode2)
                        .addGap(39, 39, 39)
                        .addComponent(DocInfo2)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Doc1Dd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(DocID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DoctormailIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Dfn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Departmentnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dln2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hospitalnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hospitalname2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Departmentname2)
                            .addComponent(Dfnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DoctormailID2)
                            .addComponent(Dlnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Doctorphonenum2)
                            .addComponent(Doctorphonenumd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Insurancedetails2)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorporateID2)
                            .addComponent(COIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddressID2)
                            .addComponent(AddIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PremiumID2)
                            .addComponent(PreIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeductableID2)
                            .addComponent(DedIdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TaxBenefitsID2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SAVE2)
                        .addGap(310, 310, 310))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Zipcoded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddIDd1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel AddressID2;
    private javax.swing.JLabel Areaname2;
    private javax.swing.JTextField Areanamed1;
    private javax.swing.JTextField COIDd1;
    private javax.swing.JLabel Cityname2;
    private javax.swing.JTextField Citynamed1;
    private javax.swing.JLabel CorporateID2;
    private javax.swing.JLabel Country2;
    private javax.swing.JTextField DedIdd1;
    private javax.swing.JLabel DeductableID2;
    private javax.swing.JLabel Departmentname2;
    private javax.swing.JTextField Departmentnamed1;
    private javax.swing.JLabel Dfn2;
    private javax.swing.JTextField Dfnd1;
    private javax.swing.JLabel Dln2;
    private javax.swing.JTextField Dlnd1;
    private javax.swing.JTextField Doc1Dd1;
    private javax.swing.JLabel DocID2;
    private javax.swing.JLabel DocInfo2;
    private javax.swing.JLabel DoctormailID2;
    private javax.swing.JTextField DoctormailIDd1;
    private javax.swing.JLabel Doctorphonenum2;
    private javax.swing.JTextField Doctorphonenumd1;
    private javax.swing.JLabel Doornum2;
    private javax.swing.JTextField Doornumd1;
    private javax.swing.JLabel Hospitalname2;
    private javax.swing.JTextField Hospitalnamed1;
    private javax.swing.JLabel Insurancedetails2;
    private javax.swing.JTextField PreIDd1;
    private javax.swing.JLabel PremiumID2;
    private javax.swing.JButton SAVE2;
    private javax.swing.JLabel State2;
    private javax.swing.JTextField Statenamed1;
    private javax.swing.JLabel Streetname2;
    private javax.swing.JTextField Streetnamed1;
    private javax.swing.JLabel TaxBenefitsID2;
    private javax.swing.JTextArea Taxbend1;
    private javax.swing.JLabel Zipcode2;
    private javax.swing.JTextField Zipcoded1;
    private javax.swing.JTextField countryd1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
