/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package UI;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author advai
 */
public class PersonalPanel extends javax.swing.JPanel {

    /** Creates new form PersonalPanel */
    Person person;
    public PersonalPanel(Person person) {
        initComponents();
        this.person = person;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        EmailID = new javax.swing.JLabel();
        ContactNum = new javax.swing.JLabel();
        EmergencyContactname = new javax.swing.JLabel();
        EmergencyContactnum = new javax.swing.JLabel();
        SSN = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        FNdesc = new javax.swing.JTextField();
        MNdesc = new javax.swing.JTextField();
        LNDesc = new javax.swing.JTextField();
        EIDDesc = new javax.swing.JTextField();
        CNdesc = new javax.swing.JTextField();
        ECNamDesc = new javax.swing.JTextField();
        EconNumDesc = new javax.swing.JTextField();
        SSNdesc = new javax.swing.JTextField();
        DOBdesc = new javax.swing.JTextField();
        GenderDesc = new javax.swing.JTextField();
        PersonalDet = new javax.swing.JLabel();
        SAVE = new javax.swing.JButton();

        FirstName.setText("FirstName:");

        MiddleName.setText("MiddleName:");

        LastName.setText("LastName:");

        EmailID.setText("EmailID:");

        ContactNum.setText("ContactNumber:");

        EmergencyContactname.setText("EmergencyContactName:");

        EmergencyContactnum.setText("EmergencyContactNum:");

        SSN.setText("SSN:");

        DOB.setText("DOB:");

        Gender.setText("Gender:");

        PersonalDet.setText("PersonalDetails");

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender)
                                    .addComponent(DOB)
                                    .addComponent(SSN)
                                    .addComponent(EmergencyContactnum))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SSNdesc)
                                    .addComponent(EconNumDesc)
                                    .addComponent(DOBdesc)
                                    .addComponent(GenderDesc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                                .addComponent(FNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MiddleName)
                                    .addComponent(LastName))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MNdesc)
                                    .addComponent(LNDesc)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailID)
                                    .addComponent(ContactNum))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EIDDesc)
                                    .addComponent(CNdesc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(EmergencyContactname)
                                .addGap(18, 18, 18)
                                .addComponent(ECNamDesc))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(PersonalDet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(SAVE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PersonalDet)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FirstName)
                            .addComponent(FNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MiddleName)
                            .addComponent(MNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(LastName)
                        .addGap(24, 24, 24)
                        .addComponent(EmailID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LNDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EIDDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactNum)
                    .addComponent(CNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmergencyContactname)
                    .addComponent(ECNamDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmergencyContactnum)
                    .addComponent(EconNumDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SSN)
                    .addComponent(SSNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB)
                    .addComponent(DOBdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender)
                    .addComponent(GenderDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SAVE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        
        
        person.setContactNum(CNdesc.getText());
        person.setDateOfBirth(DOBdesc.getText());
        person.setEmailID(EIDDesc.getText());
        person.setEmergencyContactName(ECNamDesc.getText());
        person.setEmergencyContactnum(EconNumDesc.getText());
        person.setFName(FNdesc.getText());
        person.setGender(GenderDesc.getText());
        person.setLName(LNDesc.getText());
        person.setMName(MNdesc.getText());
        person.setSSN(SSNdesc.getText());
        
        JOptionPane.showMessageDialog(this,"SAVED");
        
        
        
        
    }//GEN-LAST:event_SAVEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNdesc;
    private javax.swing.JLabel ContactNum;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOBdesc;
    private javax.swing.JTextField ECNamDesc;
    private javax.swing.JTextField EIDDesc;
    private javax.swing.JTextField EconNumDesc;
    private javax.swing.JLabel EmailID;
    private javax.swing.JLabel EmergencyContactname;
    private javax.swing.JLabel EmergencyContactnum;
    private javax.swing.JTextField FNdesc;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField GenderDesc;
    private javax.swing.JTextField LNDesc;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField MNdesc;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JLabel PersonalDet;
    private javax.swing.JButton SAVE;
    private javax.swing.JLabel SSN;
    private javax.swing.JTextField SSNdesc;
    // End of variables declaration//GEN-END:variables

}
