/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.VehicleRegistration;

/**
 *
 * @author advai
 */
public class VehicleregPanel extends javax.swing.JPanel {

    /**
     * Creates new form VehicleregPanel
     */
    
    VehicleRegistration vehicleregistration;
    
    public VehicleregPanel(VehicleRegistration vehicleregistration) {
        
        
        initComponents();
        this.vehicleregistration = vehicleregistration;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Vehicletypedesc = new javax.swing.JLabel();
        Vehiclemodeldesc = new javax.swing.JLabel();
        Vehiclecolourdesc = new javax.swing.JLabel();
        Vehiclenumdesc = new javax.swing.JLabel();
        VTdes = new javax.swing.JTextField();
        VMdes = new javax.swing.JTextField();
        Vcolourdes = new javax.swing.JTextField();
        VNumdes = new javax.swing.JTextField();
        Vehicleregistrationdesc = new javax.swing.JLabel();

        Vehicletypedesc.setText("VehicleType:");

        Vehiclemodeldesc.setText("VehicleModel:");

        Vehiclecolourdesc.setText("Vehiclecolour:");

        Vehiclenumdesc.setText("VehicleNumber:");

        Vehicleregistrationdesc.setText("Vehicleregistration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Vehiclenumdesc)
                            .addComponent(Vehiclecolourdesc)
                            .addComponent(Vehiclemodeldesc)
                            .addComponent(Vehicletypedesc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(VTdes, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(VMdes)
                            .addComponent(Vcolourdes)
                            .addComponent(VNumdes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(Vehicleregistrationdesc)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Vehicleregistrationdesc)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehicletypedesc)
                    .addComponent(VTdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehiclemodeldesc)
                    .addComponent(VMdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehiclecolourdesc)
                    .addComponent(Vcolourdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Vehiclenumdesc)
                    .addComponent(VNumdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VMdes;
    private javax.swing.JTextField VNumdes;
    private javax.swing.JTextField VTdes;
    private javax.swing.JTextField Vcolourdes;
    private javax.swing.JLabel Vehiclecolourdesc;
    private javax.swing.JLabel Vehiclemodeldesc;
    private javax.swing.JLabel Vehiclenumdesc;
    private javax.swing.JLabel Vehicleregistrationdesc;
    private javax.swing.JLabel Vehicletypedesc;
    // End of variables declaration//GEN-END:variables
}
