/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import model.Patient;
import model.Person;

/**
 *
 * @author advai
 */
public class ViewReport extends javax.swing.JPanel {

    /**
     * Creates new form ViewReport
     */
    Patient patient;
    Person person;
    public ViewReport(Patient patient, Person person) {
        initComponents();
        this.patient = patient;
        this.person = person;
        
    }

   // ViewReport(Patient patient, Person person) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        

    //}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientScreen1 = new javax.swing.JLabel();
        PatientID2 = new javax.swing.JLabel();
        DateofLV1 = new javax.swing.JLabel();
        DateofNA1 = new javax.swing.JLabel();
        Allergies_y_n1 = new javax.swing.JLabel();
        Medication_y_n1 = new javax.swing.JLabel();
        SetPatientID1 = new javax.swing.JTextField();
        SetDOLV1 = new javax.swing.JTextField();
        SetDofNA1 = new javax.swing.JTextField();
        Allergiesyn1 = new javax.swing.JTextField();
        Medicationyn1 = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        EmailID = new javax.swing.JLabel();
        ContactNum = new javax.swing.JLabel();
        EmergencyContactname = new javax.swing.JLabel();
        EmergencyContactnum = new javax.swing.JLabel();
        SSN = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        FNdesc = new javax.swing.JTextField();
        MNdesc = new javax.swing.JTextField();
        LNDesc = new javax.swing.JTextField();
        EIDDesc = new javax.swing.JTextField();
        CNdesc = new javax.swing.JTextField();
        ECNamDesc = new javax.swing.JTextField();
        EconNumDesc = new javax.swing.JTextField();
        SSNdesc = new javax.swing.JTextField();
        DOBdesc = new javax.swing.JTextField();
        GenderDesc = new javax.swing.JTextField();
        PersonalDet = new javax.swing.JLabel();

        PatientScreen1.setText("PatientDetails");

        PatientID2.setText("PatientID:");

        DateofLV1.setText("DateofLastVisit:");

        DateofNA1.setText("DateofNextAppointment:");

        Allergies_y_n1.setText("Allergies(yes/no):");

        Medication_y_n1.setText("Medication(yes/no):");

        SetPatientID1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FirstName.setText("FirstName:");

        MiddleName.setText("MiddleName:");

        LastName.setText("LastName:");

        EmailID.setText("EmailID:");

        ContactNum.setText("ContactNumber:");

        EmergencyContactname.setText("EmergencyContactName:");

        EmergencyContactnum.setText("EmergencyContactNum:");

        SSN.setText("SSN:");

        DOB.setText("DOB:");

        Gender.setText("Gender:");

        PersonalDet.setText("PersonalDetails");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(EmergencyContactnum))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Gender)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(DOB)
                                                .addComponent(SSN)))))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactNum)
                                    .addComponent(EmergencyContactname)
                                    .addComponent(EmailID)
                                    .addComponent(LastName)
                                    .addComponent(MiddleName)
                                    .addComponent(FirstName))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ECNamDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(EconNumDesc)
                            .addComponent(SSNdesc)
                            .addComponent(CNdesc)
                            .addComponent(EIDDesc)
                            .addComponent(LNDesc)
                            .addComponent(MNdesc)
                            .addComponent(FNdesc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(GenderDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(DOBdesc, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(PersonalDet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(141, 141, 141)
                            .addComponent(PatientScreen1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(DateofLV1)
                                .addComponent(PatientID2)
                                .addComponent(DateofNA1)
                                .addComponent(Allergies_y_n1)
                                .addComponent(Medication_y_n1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Medicationyn1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addComponent(SetDOLV1)
                                .addComponent(SetPatientID1)
                                .addComponent(SetDofNA1)
                                .addComponent(Allergiesyn1))))
                    .addGap(21, 21, 21)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(452, Short.MAX_VALUE)
                .addComponent(PersonalDet)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(FirstName)
                                .addGap(18, 18, 18)
                                .addComponent(MiddleName))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LNDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EIDDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EmailID)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ECNamDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyContactname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmergencyContactnum)
                    .addComponent(EconNumDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SSN)
                    .addComponent(SSNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DOB)
                    .addComponent(DOBdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addComponent(PatientScreen1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PatientID2)
                        .addComponent(SetPatientID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateofLV1)
                        .addComponent(SetDOLV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DateofNA1)
                        .addComponent(SetDofNA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Allergies_y_n1)
                        .addComponent(Allergiesyn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Medication_y_n1)
                        .addComponent(Medicationyn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(569, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Allergies_y_n1;
    private javax.swing.JTextField Allergiesyn1;
    private javax.swing.JTextField CNdesc;
    private javax.swing.JLabel ContactNum;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOBdesc;
    private javax.swing.JLabel DateofLV1;
    private javax.swing.JLabel DateofNA1;
    private javax.swing.JTextField ECNamDesc;
    private javax.swing.JTextField EIDDesc;
    private javax.swing.JTextField EconNumDesc;
    private javax.swing.JLabel EmailID;
    private javax.swing.JLabel EmergencyContactname;
    private javax.swing.JLabel EmergencyContactnum;
    private javax.swing.JTextField FNdesc;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField GenderDesc;
    private javax.swing.JTextField LNDesc;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField MNdesc;
    private javax.swing.JLabel Medication_y_n1;
    private javax.swing.JTextField Medicationyn1;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JLabel PatientID2;
    private javax.swing.JLabel PatientScreen1;
    private javax.swing.JLabel PersonalDet;
    private javax.swing.JLabel SSN;
    private javax.swing.JTextField SSNdesc;
    private javax.swing.JTextField SetDOLV1;
    private javax.swing.JTextField SetDofNA1;
    private javax.swing.JTextField SetPatientID1;
    // End of variables declaration//GEN-END:variables
}
