/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.Address;
import model.Doctor;
import model.Driver;
import model.Insurance;
import model.Patient;
import model.Person;
import model.VehicleRegistration;
/**
 *
 * @author advai
 */
public class ViewTryReport extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    Patient patient;
    Person person;
    Doctor doctor;
    VehicleRegistration vehicleregistration;
    Driver driver;
    Address address;
    Insurance insurance;
    
    public ViewTryReport(Patient patient, Person person, Driver driver, VehicleRegistration vehicleregistration,Address address,Doctor doctor,Insurance insurance) {
        initComponents();
        this.patient = patient;
        this.person = person;
        this.doctor =doctor;
        this.vehicleregistration =vehicleregistration;
        this.driver = driver;
        this.address = address;
        this.insurance =insurance;
        
        getDisplayInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        PatientScreen = new javax.swing.JLabel();
        PatientID1 = new javax.swing.JLabel();
        DateofLV = new javax.swing.JLabel();
        DateofNA = new javax.swing.JLabel();
        Allergies_y_n = new javax.swing.JLabel();
        Medication_y_n = new javax.swing.JLabel();
        SetPatientID = new javax.swing.JTextField();
        SetDOLV = new javax.swing.JTextField();
        SetDofNA = new javax.swing.JTextField();
        Allergiesyn = new javax.swing.JTextField();
        Medicationyn = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        MiddleName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        EmailID = new javax.swing.JLabel();
        ContactNum = new javax.swing.JLabel();
        EmergencyContactname = new javax.swing.JLabel();
        EmergencyContactnum = new javax.swing.JLabel();
        SSN = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        FNdesc = new javax.swing.JTextField();
        MNdesc = new javax.swing.JTextField();
        LNDesc = new javax.swing.JTextField();
        EIDDesc = new javax.swing.JTextField();
        CNdesc = new javax.swing.JTextField();
        ECNamDesc = new javax.swing.JTextField();
        EconNumDesc = new javax.swing.JTextField();
        SSNdesc = new javax.swing.JTextField();
        DOBdesc = new javax.swing.JTextField();
        GenderDesc = new javax.swing.JTextField();
        PersonalDet = new javax.swing.JLabel();
        Drivername = new javax.swing.JLabel();
        DLNum = new javax.swing.JLabel();
        Vehicletype = new javax.swing.JLabel();
        Expirydate = new javax.swing.JLabel();
        Dateofbirth = new javax.swing.JLabel();
        DNamedes = new javax.swing.JTextField();
        DLnumdes = new javax.swing.JTextField();
        Vehicletypenum = new javax.swing.JTextField();
        Expirydatedes = new javax.swing.JTextField();
        DOBdesc1 = new javax.swing.JTextField();
        Vehicletypedesc = new javax.swing.JLabel();
        Vehiclemodeldesc = new javax.swing.JLabel();
        Vehiclecolourdesc = new javax.swing.JLabel();
        Vehiclenumdesc = new javax.swing.JLabel();
        Vehicleregistrationdesc = new javax.swing.JLabel();
        VTdes = new javax.swing.JTextField();
        VMdes = new javax.swing.JTextField();
        Vcolourdes = new javax.swing.JTextField();
        VNumdes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        Doornum2 = new javax.swing.JLabel();
        Streetname2 = new javax.swing.JLabel();
        Areaname2 = new javax.swing.JLabel();
        Cityname2 = new javax.swing.JLabel();
        State2 = new javax.swing.JLabel();
        Country2 = new javax.swing.JLabel();
        Zipcode2 = new javax.swing.JLabel();
        Doornumd1 = new javax.swing.JTextField();
        Streetnamed1 = new javax.swing.JTextField();
        Areanamed1 = new javax.swing.JTextField();
        Citynamed1 = new javax.swing.JTextField();
        Statenamed1 = new javax.swing.JTextField();
        countryd1 = new javax.swing.JTextField();
        Zipcoded1 = new javax.swing.JTextField();
        DocInfo2 = new javax.swing.JLabel();
        DocID2 = new javax.swing.JLabel();
        Dfn2 = new javax.swing.JLabel();
        Dln2 = new javax.swing.JLabel();
        Hospitalname2 = new javax.swing.JLabel();
        Departmentname2 = new javax.swing.JLabel();
        DoctormailID2 = new javax.swing.JLabel();
        Doctorphonenum2 = new javax.swing.JLabel();
        Doc1Dd1 = new javax.swing.JTextField();
        Dfnd1 = new javax.swing.JTextField();
        Dlnd1 = new javax.swing.JTextField();
        Hospitalnamed1 = new javax.swing.JTextField();
        Departmentnamed1 = new javax.swing.JTextField();
        DoctormailIDd1 = new javax.swing.JTextField();
        Doctorphonenumd1 = new javax.swing.JTextField();
        Insurancedetails2 = new javax.swing.JLabel();
        CorporateID2 = new javax.swing.JLabel();
        AddressID2 = new javax.swing.JLabel();
        PremiumID2 = new javax.swing.JLabel();
        DeductableID2 = new javax.swing.JLabel();
        TaxBenefitsID2 = new javax.swing.JLabel();
        SAVE2 = new javax.swing.JButton();
        COIDd1 = new javax.swing.JTextField();
        AddIDd1 = new javax.swing.JTextField();
        PreIDd1 = new javax.swing.JTextField();
        DedIdd1 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 2389));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 458));

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 2446));

        PatientScreen.setText("PatientDetails");

        PatientID1.setText("PatientID:");

        DateofLV.setText("DateofLastVisit:");

        DateofNA.setText("DateofNextAppointment:");

        Allergies_y_n.setText("Allergies(yes/no):");

        Medication_y_n.setText("Medication(yes/no):");

        SetPatientID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        FirstName.setText("FirstName:");

        MiddleName.setText("MiddleName:");

        LastName.setText("LastName:");

        EmailID.setText("EmailID:");

        ContactNum.setText("ContactNumber:");

        EmergencyContactname.setText("EmergencyContactName:");

        EmergencyContactnum.setText("EmergencyContactNum:");

        SSN.setText("SSN:");

        DOB.setText("DOB:");

        Gender.setText("Gender:");

        ECNamDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ECNamDescActionPerformed(evt);
            }
        });

        PersonalDet.setText("PersonalDetails");

        Drivername.setText("DriverName:");

        DLNum.setText("DriverslicenseNumber:");

        Vehicletype.setText("VehicleType:");

        Expirydate.setText("ExpiryDate:");

        Dateofbirth.setText("DOB:");

        Vehicletypedesc.setText("VehicleType:");

        Vehiclemodeldesc.setText("VehicleModel:");

        Vehiclecolourdesc.setText("Vehiclecolour:");

        Vehiclenumdesc.setText("VehicleNumber:");

        Vehicleregistrationdesc.setText("Vehicleregistration");

        jLabel1.setText("Driver Details");

        Address2.setText("Address");

        Doornum2.setText("DoorNum:");

        Streetname2.setText("StreetName:");

        Areaname2.setText("AreaName:");

        Cityname2.setText("CityName:");

        State2.setText("State:");

        Country2.setText("Country:");

        Zipcode2.setText("Zipcode:");

        DocInfo2.setText("Doctorinformation");

        DocID2.setText("DoctorID:");

        Dfn2.setText("FirstName:");

        Dln2.setText("LastName:");

        Hospitalname2.setText("HospitalName:");

        Departmentname2.setText("DepartmentName:");

        DoctormailID2.setText("DoctormailID:");

        Doctorphonenum2.setText("Doctorphonenum:");

        Insurancedetails2.setText("Insurancedetails");

        CorporateID2.setText("CorporateID:");

        AddressID2.setText("Address:");

        PremiumID2.setText("Premium:");

        DeductableID2.setText("Deductable:");

        TaxBenefitsID2.setText("TaxBenefits:");

        SAVE2.setText("SAVE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DateofLV)
                            .addComponent(PatientID1)
                            .addComponent(DateofNA)
                            .addComponent(Allergies_y_n)
                            .addComponent(Medication_y_n))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Medicationyn, javax.swing.GroupLayout.DEFAULT_SIZE, 2326, Short.MAX_VALUE)
                            .addComponent(SetDOLV)
                            .addComponent(SetPatientID)
                            .addComponent(SetDofNA)
                            .addComponent(Allergiesyn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(PatientScreen)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(FirstName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(FNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MiddleName)
                                    .addComponent(LastName))
                                .addGap(77, 77, 77)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MNdesc)
                                    .addComponent(LNDesc)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmailID)
                                    .addComponent(ContactNum))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EIDDesc)
                                    .addComponent(CNdesc)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(EmergencyContactname)
                                .addGap(18, 18, 18)
                                .addComponent(ECNamDesc))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(PersonalDet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender)
                                    .addComponent(DOB)
                                    .addComponent(SSN)
                                    .addComponent(EmergencyContactnum))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(SSNdesc)
                                    .addComponent(EconNumDesc)
                                    .addComponent(DOBdesc)
                                    .addComponent(GenderDesc)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Vehiclenumdesc)
                                    .addComponent(Vehiclecolourdesc)
                                    .addComponent(Vehiclemodeldesc)
                                    .addComponent(Vehicletypedesc))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(VTdes, javax.swing.GroupLayout.DEFAULT_SIZE, 2387, Short.MAX_VALUE)
                                    .addComponent(VMdes)
                                    .addComponent(Vcolourdes)
                                    .addComponent(VNumdes)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(DLNum)
                                            .addComponent(Drivername)
                                            .addComponent(Expirydate)
                                            .addComponent(Dateofbirth)
                                            .addComponent(Vehicletype))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DLnumdes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DNamedes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Vehicletypenum, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(DOBdesc1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Expirydatedes, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(Vehicleregistrationdesc)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Areaname2)
                                .addGap(104, 104, 104)
                                .addComponent(Areanamed1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Doornum2)
                                    .addComponent(Streetname2))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Streetnamed1)
                                    .addComponent(Doornumd1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Dfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(DoctormailIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(Doc1Dd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(211, 211, 211)
                                        .addComponent(Address2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CorporateID2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(COIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(104, 104, 104)
                                        .addComponent(Insurancedetails2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AddressID2)
                                            .addComponent(PremiumID2)
                                            .addComponent(DeductableID2)
                                            .addComponent(TaxBenefitsID2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SAVE2)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(DedIdd1)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(PreIDd1, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(AddIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(1, 1, 1)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Zipcode2)
                                            .addComponent(Country2)
                                            .addComponent(State2)
                                            .addComponent(Cityname2))
                                        .addGap(108, 108, 108)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Citynamed1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Statenamed1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(countryd1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Zipcoded1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Doctorphonenum2)
                                            .addComponent(DoctormailID2)
                                            .addComponent(Departmentname2)
                                            .addComponent(Hospitalname2)
                                            .addComponent(Dln2)
                                            .addComponent(DocID2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DocInfo2)
                                            .addComponent(Departmentnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Hospitalnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dfnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dlnd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Doctorphonenumd1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PatientScreen)
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PatientID1)
                            .addComponent(SetPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateofLV)
                            .addComponent(SetDOLV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DateofNA)
                            .addComponent(SetDofNA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Allergies_y_n)
                            .addComponent(Allergiesyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Medication_y_n)
                            .addComponent(Medicationyn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(PersonalDet)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FirstName)
                                    .addComponent(FNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(MiddleName)
                                    .addComponent(MNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addComponent(LastName)
                                .addGap(24, 24, 24)
                                .addComponent(EmailID))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LNDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EIDDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ContactNum)
                            .addComponent(CNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmergencyContactname)
                            .addComponent(ECNamDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmergencyContactnum)
                            .addComponent(EconNumDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SSN)
                            .addComponent(SSNdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB)
                            .addComponent(DOBdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender)
                            .addComponent(GenderDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Drivername)
                            .addComponent(DNamedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DLNum)
                            .addComponent(DLnumdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vehicletype)
                            .addComponent(Vehicletypenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Expirydatedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Expirydate))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dateofbirth)
                            .addComponent(DOBdesc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(Vehicleregistrationdesc)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vehicletypedesc)
                            .addComponent(VTdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vehiclemodeldesc)
                            .addComponent(VMdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vehiclecolourdesc)
                            .addComponent(Vcolourdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vehiclenumdesc)
                            .addComponent(VNumdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Address2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Doornum2)
                                    .addComponent(Doornumd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Streetname2)
                                .addGap(6, 6, 6))
                            .addComponent(Streetnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Areaname2)
                            .addComponent(Areanamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cityname2)
                            .addComponent(Citynamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(State2)
                            .addComponent(Statenamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Country2)
                            .addComponent(countryd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Zipcode2)
                            .addComponent(Zipcoded1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(DocInfo2)
                        .addGap(31, 31, 31)
                        .addComponent(DocID2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Dfn2, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                            .addComponent(Doc1Dd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DoctormailIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Departmentnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dln2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Hospitalnamed1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hospitalname2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Departmentname2)
                    .addComponent(Dfnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctormailID2)
                    .addComponent(Dlnd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Doctorphonenum2)
                    .addComponent(Doctorphonenumd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Insurancedetails2)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorporateID2)
                    .addComponent(COIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddressID2)
                    .addComponent(AddIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PremiumID2)
                    .addComponent(PreIDd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeductableID2)
                    .addComponent(DedIdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(TaxBenefitsID2)
                .addGap(50, 50, 50)
                .addComponent(SAVE2)
                .addGap(446, 446, 446))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ECNamDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ECNamDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ECNamDescActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddIDd1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel AddressID2;
    private javax.swing.JLabel Allergies_y_n;
    private javax.swing.JTextField Allergiesyn;
    private javax.swing.JLabel Areaname2;
    private javax.swing.JTextField Areanamed1;
    private javax.swing.JTextField CNdesc;
    private javax.swing.JTextField COIDd1;
    private javax.swing.JLabel Cityname2;
    private javax.swing.JTextField Citynamed1;
    private javax.swing.JLabel ContactNum;
    private javax.swing.JLabel CorporateID2;
    private javax.swing.JLabel Country2;
    private javax.swing.JLabel DLNum;
    private javax.swing.JTextField DLnumdes;
    private javax.swing.JTextField DNamedes;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField DOBdesc;
    private javax.swing.JTextField DOBdesc1;
    private javax.swing.JLabel DateofLV;
    private javax.swing.JLabel DateofNA;
    private javax.swing.JLabel Dateofbirth;
    private javax.swing.JTextField DedIdd1;
    private javax.swing.JLabel DeductableID2;
    private javax.swing.JLabel Departmentname2;
    private javax.swing.JTextField Departmentnamed1;
    private javax.swing.JLabel Dfn2;
    private javax.swing.JTextField Dfnd1;
    private javax.swing.JLabel Dln2;
    private javax.swing.JTextField Dlnd1;
    private javax.swing.JTextField Doc1Dd1;
    private javax.swing.JLabel DocID2;
    private javax.swing.JLabel DocInfo2;
    private javax.swing.JLabel DoctormailID2;
    private javax.swing.JTextField DoctormailIDd1;
    private javax.swing.JLabel Doctorphonenum2;
    private javax.swing.JTextField Doctorphonenumd1;
    private javax.swing.JLabel Doornum2;
    private javax.swing.JTextField Doornumd1;
    private javax.swing.JLabel Drivername;
    private javax.swing.JTextField ECNamDesc;
    private javax.swing.JTextField EIDDesc;
    private javax.swing.JTextField EconNumDesc;
    private javax.swing.JLabel EmailID;
    private javax.swing.JLabel EmergencyContactname;
    private javax.swing.JLabel EmergencyContactnum;
    private javax.swing.JLabel Expirydate;
    private javax.swing.JTextField Expirydatedes;
    private javax.swing.JTextField FNdesc;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JTextField GenderDesc;
    private javax.swing.JLabel Hospitalname2;
    private javax.swing.JTextField Hospitalnamed1;
    private javax.swing.JLabel Insurancedetails2;
    private javax.swing.JTextField LNDesc;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField MNdesc;
    private javax.swing.JLabel Medication_y_n;
    private javax.swing.JTextField Medicationyn;
    private javax.swing.JLabel MiddleName;
    private javax.swing.JLabel PatientID1;
    private javax.swing.JLabel PatientScreen;
    private javax.swing.JLabel PersonalDet;
    private javax.swing.JTextField PreIDd1;
    private javax.swing.JLabel PremiumID2;
    private javax.swing.JButton SAVE2;
    private javax.swing.JLabel SSN;
    private javax.swing.JTextField SSNdesc;
    private javax.swing.JTextField SetDOLV;
    private javax.swing.JTextField SetDofNA;
    private javax.swing.JTextField SetPatientID;
    private javax.swing.JLabel State2;
    private javax.swing.JTextField Statenamed1;
    private javax.swing.JLabel Streetname2;
    private javax.swing.JTextField Streetnamed1;
    private javax.swing.JLabel TaxBenefitsID2;
    private javax.swing.JTextField VMdes;
    private javax.swing.JTextField VNumdes;
    private javax.swing.JTextField VTdes;
    private javax.swing.JTextField Vcolourdes;
    private javax.swing.JLabel Vehiclecolourdesc;
    private javax.swing.JLabel Vehiclemodeldesc;
    private javax.swing.JLabel Vehiclenumdesc;
    private javax.swing.JLabel Vehicleregistrationdesc;
    private javax.swing.JLabel Vehicletype;
    private javax.swing.JLabel Vehicletypedesc;
    private javax.swing.JTextField Vehicletypenum;
    private javax.swing.JLabel Zipcode2;
    private javax.swing.JTextField Zipcoded1;
    private javax.swing.JTextField countryd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void getDisplayInfo() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        
        SetPatientID.setText(patient.getPatientID());
        SetDOLV.setText(patient.getDateofLV());
        SetDofNA.setText(patient.getNextAppointment());
        Allergiesyn.setText(patient.getAllergies());
        Medicationyn.setText(patient.getMedication());
        
        
        
        FNdesc.setText(person.getFName());
        MNdesc.setText(person.getMName());
        LNDesc.setText(person.getLName());
        CNdesc.setText(person.getContactNum());
        ECNamDesc.setText(person.getEmergencyContactName());
        
        
                
    }
    
    
}
